version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: minyus86/client:0.2.4
    container_name: client
    # privileged: true
    # environment: []
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ../../:/data
    # ports: []
    network_mode: host
    # networks:
        # - kind
# networks:
  # kind:
    # external: true
