version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: minyus86/client:1.1.0
    container_name: client
    # privileged: true
    # environment: []
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ~/.kube/:/root/.kube/
      - ~/.ssh/:/root/.ssh/
      - ../../:/data
    # ports: []
    network_mode: host
