version: "3"
services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    image: minyus86/ml:v0.4.0-cuda10.1-cudnn7-runtime
    container_name: ml04
    # privileged: true
    environment: []
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ../../:/data
    ports:
      - 4141:4141
      - 5000:5000
      - 6006:6006
      - 8000:8000
      - 8888:8888
      - 8889:8889
#     network_mode: host
#     networks:
#         - kind
# networks:
#   kind:
#     external: true
